name: Build Maps
on: [push]
jobs:
  create-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run script
        run: python3 germany_plot_v04.py
      - name: Archive images
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: output/*
